// <auto-generated />
using System;
using AUTistima.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AUTistima.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251205205050_AddUserPersonalFields")]
    partial class AddUserPersonalFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("autistima_sa_sql")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AUTistima.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CEP")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("CNPJ")
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("CPF")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("EmpresaAmiga")
                        .HasColumnType("bit");

                    b.Property<string>("Endereco")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Especialidade")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("FotoPerfilUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomeEmpresa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NumeroEndereco")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RG")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("RegistroProfissional")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SobreMim")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TipoPerfil")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", "autistima_sa_sql");
                });

            modelBuilder.Entity("AUTistima.Models.Child", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataDiagnostico")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EscolaId")
                        .HasColumnType("int");

                    b.Property<string>("EscolaNome")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EstrategiasCrise")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NivelSuporte")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PossuiDiagnostico")
                        .HasColumnType("bit");

                    b.Property<bool>("PossuiPAE")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EscolaId");

                    b.HasIndex("UserId");

                    b.ToTable("Children", "autistima_sa_sql");
                });

            modelBuilder.Entity("AUTistima.Models.GlossaryTerm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExemploUso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExplicacaoSimples")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fonte")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TermoTecnico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.HasIndex("TermoTecnico");

                    b.ToTable("GlossaryTerms", "autistima_sa_sql");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Categoria = "Diagnóstico",
                            DataCriacao = new DateTime(2025, 12, 5, 20, 50, 49, 584, DateTimeKind.Utc).AddTicks(8730),
                            ExplicacaoSimples = "Transtorno do Espectro Autista - é uma condição do neurodesenvolvimento que afeta a comunicação, interação social e comportamento. Cada pessoa autista é única.",
                            TermoTecnico = "TEA"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Categoria = "Comportamento",
                            DataCriacao = new DateTime(2025, 12, 5, 20, 50, 49, 584, DateTimeKind.Utc).AddTicks(9080),
                            ExplicacaoSimples = "Movimentos repetitivos que a pessoa autista faz, como balançar o corpo, bater as mãos ou girar objetos. São formas de autorregulação e não devem ser reprimidas.",
                            TermoTecnico = "Estereotipia"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Categoria = "Comportamento",
                            DataCriacao = new DateTime(2025, 12, 5, 20, 50, 49, 584, DateTimeKind.Utc).AddTicks(9080),
                            ExplicacaoSimples = "Quando a pessoa autista tem um interesse muito intenso por um assunto específico. Pode ser uma força quando bem direcionado.",
                            TermoTecnico = "Hiperfoco"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Categoria = "Comportamento",
                            DataCriacao = new DateTime(2025, 12, 5, 20, 50, 49, 584, DateTimeKind.Utc).AddTicks(9080),
                            ExplicacaoSimples = "Uma crise intensa causada por sobrecarga sensorial ou emocional. Não é birra - é o corpo reagindo a algo insuportável. Requer paciência e ambiente calmo.",
                            TermoTecnico = "Meltdown"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Categoria = "Comportamento",
                            DataCriacao = new DateTime(2025, 12, 5, 20, 50, 49, 584, DateTimeKind.Utc).AddTicks(9080),
                            ExplicacaoSimples = "Quando a pessoa 'desliga' por estar sobrecarregada. Pode ficar quieta, não responder, parecer distante. É uma forma de proteção do cérebro.",
                            TermoTecnico = "Shutdown"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            Categoria = "Sensorial",
                            DataCriacao = new DateTime(2025, 12, 5, 20, 50, 49, 584, DateTimeKind.Utc).AddTicks(9080),
                            ExplicacaoSimples = "Quando os sentidos (audição, visão, tato, olfato, paladar) são mais intensos. Um som normal pode doer, uma luz pode incomodar muito, algumas texturas são insuportáveis.",
                            TermoTecnico = "Sensibilidade Sensorial"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            Categoria = "Comunicação",
                            DataCriacao = new DateTime(2025, 12, 5, 20, 50, 49, 584, DateTimeKind.Utc).AddTicks(9090),
                            ExplicacaoSimples = "Repetir palavras ou frases ouvidas. Pode ser imediata ou depois de um tempo. É uma forma de comunicação e processamento de linguagem.",
                            TermoTecnico = "Ecolalia"
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            Categoria = "Educação",
                            DataCriacao = new DateTime(2025, 12, 5, 20, 50, 49, 584, DateTimeKind.Utc).AddTicks(9090),
                            ExplicacaoSimples = "Plano de Atendimento Educacional - documento que a escola deve fazer para adaptar o ensino às necessidades do aluno autista. É um direito garantido por lei.",
                            TermoTecnico = "PAE"
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            Categoria = "Terapia",
                            DataCriacao = new DateTime(2025, 12, 5, 20, 50, 49, 584, DateTimeKind.Utc).AddTicks(9090),
                            ExplicacaoSimples = "Análise do Comportamento Aplicada - uma terapia comportamental usada para desenvolver habilidades. Deve ser aplicada de forma ética e respeitosa.",
                            TermoTecnico = "ABA"
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            Categoria = "Geral",
                            DataCriacao = new DateTime(2025, 12, 5, 20, 50, 49, 584, DateTimeKind.Utc).AddTicks(9090),
                            ExplicacaoSimples = "Pessoa cujo cérebro funciona de forma diferente do padrão. Inclui autistas, pessoas com TDAH, dislexia e outras condições. Não é doença, é diversidade.",
                            TermoTecnico = "Neurodivergente"
                        },
                        new
                        {
                            Id = 11,
                            Ativo = true,
                            Categoria = "Diagnóstico",
                            DataCriacao = new DateTime(2025, 12, 5, 20, 50, 49, 584, DateTimeKind.Utc).AddTicks(9090),
                            ExplicacaoSimples = "Quando a pessoa tem mais de uma condição ao mesmo tempo. Por exemplo, autismo junto com TDAH, ansiedade ou epilepsia.",
                            TermoTecnico = "Comorbidade"
                        },
                        new
                        {
                            Id = 12,
                            Ativo = true,
                            Categoria = "Alimentação",
                            DataCriacao = new DateTime(2025, 12, 5, 20, 50, 49, 584, DateTimeKind.Utc).AddTicks(9090),
                            ExplicacaoSimples = "Quando a pessoa aceita poucos alimentos. Está relacionada à sensibilidade sensorial (textura, cor, cheiro). Não é frescura ou falta de educação.",
                            TermoTecnico = "Seletividade Alimentar"
                        });
                });

            modelBuilder.Entity("AUTistima.Models.Manejo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DicaPratica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EspecialistaValidadorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FaixaEtariaIndicada")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("NivelSuporteIndicado")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("ValidadoPorEspecialista")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.HasIndex("EspecialistaValidadorId");

                    b.HasIndex("UserId");

                    b.ToTable("Manejos", "autistima_sa_sql");
                });

            modelBuilder.Entity("AUTistima.Models.Opportunity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Beneficios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Contato")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataExpiracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<bool>("HorarioFlexivel")
                        .HasColumnType("bit");

                    b.Property<string>("LinkExterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PermiteHomeOffice")
                        .HasColumnType("bit");

                    b.Property<string>("Requisitos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ValorSalario")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DataCriacao");

                    b.HasIndex("Tipo");

                    b.HasIndex("UserId");

                    b.ToTable("Opportunities", "autistima_sa_sql");
                });

            modelBuilder.Entity("AUTistima.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PermitirComentarios")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DataCriacao");

                    b.HasIndex("UserId");

                    b.ToTable("Posts", "autistima_sa_sql");
                });

            modelBuilder.Entity("AUTistima.Models.PostAcolhimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAcolhimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("PostId", "UserId")
                        .IsUnique();

                    b.ToTable("PostAcolhimentos", "autistima_sa_sql");
                });

            modelBuilder.Entity("AUTistima.Models.PostComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("PostComments", "autistima_sa_sql");
                });

            modelBuilder.Entity("AUTistima.Models.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CEP")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("CNPJ")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EscolaPublica")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("PossuiSalaRecursos")
                        .HasColumnType("bit");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CNPJ")
                        .IsUnique()
                        .HasFilter("[CNPJ] IS NOT NULL");

                    b.ToTable("Schools", "autistima_sa_sql");
                });

            modelBuilder.Entity("AUTistima.Models.ScreeningRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoIdentificador")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContextoObservacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAvaliacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Encaminhamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EscolaId")
                        .HasColumnType("int");

                    b.Property<int?>("IdadeAluno")
                        .HasColumnType("int");

                    b.Property<string>("NomeAluno")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ParecerProfissional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfessorSolicitanteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProfissionalResponsavelId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Recomendacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerieAno")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SinaisObservados")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EscolaId");

                    b.HasIndex("ProfessorSolicitanteId");

                    b.HasIndex("ProfissionalResponsavelId");

                    b.HasIndex("Status");

                    b.ToTable("ScreeningRequests", "autistima_sa_sql");
                });

            modelBuilder.Entity("AUTistima.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AtendeOnline")
                        .HasColumnType("bit");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CEP")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Especialidade")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("NomeProfissional")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistroProfissional")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TipoAtendimento")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ValorConsulta")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Verificado")
                        .HasColumnType("bit");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Bairro");

                    b.HasIndex("Cidade");

                    b.HasIndex("Especialidade");

                    b.HasIndex("TipoAtendimento");

                    b.HasIndex("UserId");

                    b.ToTable("Services", "autistima_sa_sql");
                });

            modelBuilder.Entity("AUTistima.Models.SystemConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("DadoSensivel")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemConfigurations", "autistima_sa_sql");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", "autistima_sa_sql");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "autistima_sa_sql");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "autistima_sa_sql");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "autistima_sa_sql");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "autistima_sa_sql");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "autistima_sa_sql");
                });

            modelBuilder.Entity("AUTistima.Models.Child", b =>
                {
                    b.HasOne("AUTistima.Models.School", "Escola")
                        .WithMany("Alunos")
                        .HasForeignKey("EscolaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AUTistima.Models.ApplicationUser", "Usuario")
                        .WithMany("Filhos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Escola");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AUTistima.Models.Manejo", b =>
                {
                    b.HasOne("AUTistima.Models.ApplicationUser", "EspecialistaValidador")
                        .WithMany()
                        .HasForeignKey("EspecialistaValidadorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AUTistima.Models.ApplicationUser", "Autor")
                        .WithMany("Manejos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("EspecialistaValidador");
                });

            modelBuilder.Entity("AUTistima.Models.Opportunity", b =>
                {
                    b.HasOne("AUTistima.Models.ApplicationUser", "Criador")
                        .WithMany("OportunidadesCriadas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Criador");
                });

            modelBuilder.Entity("AUTistima.Models.Post", b =>
                {
                    b.HasOne("AUTistima.Models.ApplicationUser", "Autor")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("AUTistima.Models.PostAcolhimento", b =>
                {
                    b.HasOne("AUTistima.Models.Post", "Post")
                        .WithMany("Acolhimentos")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AUTistima.Models.ApplicationUser", "Usuario")
                        .WithMany("Acolhimentos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AUTistima.Models.PostComment", b =>
                {
                    b.HasOne("AUTistima.Models.Post", "Post")
                        .WithMany("Comentarios")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AUTistima.Models.ApplicationUser", "Autor")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("AUTistima.Models.ScreeningRequest", b =>
                {
                    b.HasOne("AUTistima.Models.School", "Escola")
                        .WithMany("Triagens")
                        .HasForeignKey("EscolaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AUTistima.Models.ApplicationUser", "ProfessorSolicitante")
                        .WithMany()
                        .HasForeignKey("ProfessorSolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AUTistima.Models.ApplicationUser", "ProfissionalResponsavel")
                        .WithMany()
                        .HasForeignKey("ProfissionalResponsavelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Escola");

                    b.Navigation("ProfessorSolicitante");

                    b.Navigation("ProfissionalResponsavel");
                });

            modelBuilder.Entity("AUTistima.Models.Service", b =>
                {
                    b.HasOne("AUTistima.Models.ApplicationUser", "Profissional")
                        .WithMany("Servicos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AUTistima.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AUTistima.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AUTistima.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AUTistima.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AUTistima.Models.ApplicationUser", b =>
                {
                    b.Navigation("Acolhimentos");

                    b.Navigation("Filhos");

                    b.Navigation("Manejos");

                    b.Navigation("OportunidadesCriadas");

                    b.Navigation("Posts");

                    b.Navigation("Servicos");
                });

            modelBuilder.Entity("AUTistima.Models.Post", b =>
                {
                    b.Navigation("Acolhimentos");

                    b.Navigation("Comentarios");
                });

            modelBuilder.Entity("AUTistima.Models.School", b =>
                {
                    b.Navigation("Alunos");

                    b.Navigation("Triagens");
                });
#pragma warning restore 612, 618
        }
    }
}
